# Generated by Django 2.2.7 on 2019-11-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(to='groups.Group'),
        ),
    ]
