# Generated by Django 2.2.7 on 2019-11-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_member_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['display_name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
