# Generated by Django 2.2.7 on 2019-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20191117_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='default@stolaf.edu', max_length=254),
        ),
    ]
