# Generated by Django 2.2.7 on 2019-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20191117_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
