# Generated by Django 2.2.7 on 2019-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20191117_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
